name: DIP_hw1_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipython
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - scikit-learn
  - scikit-image
  - opencv
  - pillow
  - pip:
    - matplotlib
- rawpy